version: '3.6'

services:
  nuxt:
    build: 
      context: ./nuxt-frontend
      dockerfile: Dockerfile
    image: "tqd-nuxt_image:latest"
    container_name: tqd-nuxt
    restart: always
    environment:
      - NUXT_PORT=8000
    ports:
      - 8000:8000
    command: npm run start

  api:
    build: ./server
    image: "tqd-node_image:latest"
    container_name: tqd-node
    ports:
      - 3000:3000
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - NODE_PORT=3000
     - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app/symptoms
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    networks:
      - esnet
    command: npm run start

  migration:
    build: 
      context: ./migration
      dockerfile: Dockerfile
    image: "tqd-migrate_image:latest"
    container_name: tqd-migrate
    environment:
     - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - ./migration/src/data:/usr/src/migration/src/data
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    networks:
      - esnet
    profiles: ["migrate"]
    command: npm run migrate

  elasticsearch:
    container_name: tqd-elasticsearch
    image: korolikhinanton/elastic
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    expose:
      - "9200"
    networks:
      - esnet

volumes:
  esdata:

networks:
  esnet: